
export const INC_INIT 						= 'INC_INIT'
export const INC_SIGNUP  					= 'INC_SIGNUP'
export const INC_LOGIN  					= 'INC_LOGIN'
export const INC_HOME  						= 'INC_HOME'
export const INC_DASHBOARD					= 'INC_DASHBOARD'
export const INC_BZZBOX_STATE_GRAPH			= 'INC_BZZBOX_STATE_GRAPH'
export const INC_ACTIVITY					= 'INC_ACTIVITY'
export const INC_SETTINGS					= 'INC_SETTINGS'
export const INC_ADDHIVE					= 'INC_ADDHIVE'
export const INC_EVENTS  					= 'INC_EVENTS'
export const INC_HIVE_DATA  				= 'INC_HIVE_DATA'
